{{- if and .Values.postgresql.enabled (not .Values.postgresql.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "red-potato.postgresql.fullname" . }}
  labels:
    {{- include "red-potato.postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "red-potato.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
